---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: hostname | length > 0

- name: Ensure /etc/hosts has hostname entry
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.1\.1\s+).*'
    line: "127.0.1.1   {{ hostname }}"